apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp
  namespace: {{ .Values.namespace.env }}
  labels:
    app: helloapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloapp
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
      - name: helloapp
        image: {{ .Values.image.repo }}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.type }}
  namespace: {{ .Values.namespace.env }}
spec:
  selector:
        app: helloapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
